default: &default
  adapter: postgresql
  encoding: unicode
  username: harish
  password: password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: store_development

test:
  <<: *default
  database: store_test

production:
  <<: *default
  database: store_production
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV["PG_HOST"] || "localhost" %>
